version: "3.9"

services:
  clients:
    build:
      context: ./clients
      dockerfile: Dockerfile
    ports:
      - "5174:5174"
    command: ["npm", "run", "dev", "--", "--host", "--port", "5174"]

  host:
    build:
      context: ./host
      dockerfile: Dockerfile
    environment:
      - VITE_URL_REMOTE=http://clients:5174
    ports:
      - "5173:5173"
    depends_on:
      - clients
