version: "3.9"

services:
  clients:
    build:
      context: ./clients
      dockerfile: Dockerfile.prod
    image: teddy/clients:prod
    ports:
      - "8081:80"

  host:
    build:
      context: ./host
      dockerfile: Dockerfile.prod
      args:
        # URL pública onde o browser acessará o remoto clients em produção
        VITE_URL_REMOTE: http://localhost:8081
    image: teddy/host:prod
    ports:
      - "8080:80"
    depends_on:
      - clients


